# Table Diagnostics Utilities

#' Custom order function for table rows
#'
#' @param var_name Name of the variable
#' @param row_type_val Type of row (e.g., "Coefficient", "Factor Label")
#' @return Numeric value for ordering
custom_order <- function(var_name, row_type_val) {
    if (var_name == "(Intercept)") {
        return(1)
    } else {
        base_name <- if (grepl("^[a-zA-Z_]+[A-Z]", var_name)) {
            sub("^([a-zA-Z_]+?)[A-Z].*", "\\1", var_name)
        } else {
            var_name
        }
        unique_bases <- unique(raw_model_output_tab$variable_base[raw_model_output_tab$variable_base != "(Intercept)"])
        base_to_group <- list()
        group_counter <- 2
        if (treatment_var %in% unique_bases) {
            base_to_group[[treatment_var]] <- group_counter
            group_counter <- group_counter + 1
        }
        for (base_var in unique_bases) {
            if (base_var != treatment_var && !(base_var %in% names(base_to_group))) {
                base_to_group[[base_var]] <- group_counter
                group_counter <- group_counter + 1
            }
        }
        base_priority <- base_to_group[[base_name]]
        if (row_type_val == "Factor Label") {
            return(base_priority)
        } else {
            return(base_priority + 0.5)
        }
    }
}

#' Create comprehensive diagnostics with all required tabs
#'
#' @param model_fit Fitted model object
#' @param data Data frame
#' @param outcome_var Character string name of outcome variable
#' @param predictor_vars Character vector of predictor variables
#' @param confounders Character vector of confounder variables
#' @param analysis_name Character string for analysis name
#' @param dataset_name Character string for dataset name
#' @param filtered_variables Character vector of variables that were filtered from the table
#' @param treatment_var Character string for treatment variable (default: "treatment_group")
#' @return List containing all diagnostic data frames
create_comprehensive_diagnostics <- function(model_fit, data, outcome_var, predictor_vars, confounders, analysis_name, dataset_name, filtered_variables = NULL, other_map = list(), extreme_diagnostics = NULL, treatment_var = "treatment_group") {
    
    # Get model coefficients and summary
    coefs <- coef(model_fit)
    model_summary <- summary(model_fit)
    
    # Create a temporary gtsummary table to get the confidence intervals
    temp_table <- tryCatch({
        model_fit %>%
            tbl_regression(
                exponentiate = FALSE,
                conf.int = TRUE
            )
    }, error = function(e) {
        log_enhanced(sprintf("Warning: Could not create temporary table for CI extraction: %s", e$message), level = "WARN")
        NULL
    })
    
    # Extract confidence intervals from the gtsummary table
    if (!is.null(temp_table)) {
        table_data <- temp_table$table_body
        ci_mapping <- data.frame(
            term = table_data$term,
            conf.low = table_data$conf.low,
            conf.high = table_data$conf.high,
            stringsAsFactors = FALSE
        )
        
        conf_int <- matrix(NA, nrow = length(coefs), ncol = 2,
                          dimnames = list(names(coefs), c("2.5 %", "97.5 %")))
        
        for (i in 1:nrow(ci_mapping)) {
            term_name <- ci_mapping$term[i]
            if (term_name %in% names(coefs)) {
                conf_int[term_name, "2.5 %"] <- ci_mapping$conf.low[i]
                conf_int[term_name, "97.5 %"] <- ci_mapping$conf.high[i]
            }
        }
    } else {
        conf_int <- tryCatch({
            suppressWarnings(confint(model_fit))
        }, error = function(e) {
            log_enhanced(sprintf("Warning: Could not compute confidence intervals: %s", e$message), level = "WARN")
            matrix(NA, nrow = length(coefs), ncol = 2, 
                   dimnames = list(names(coefs), c("2.5 %", "97.5 %")))
        })
    }
    
    if (all(is.na(conf_int))) {
        log_enhanced("Warning: All confidence intervals are NA - this indicates severe model convergence issues", level = "WARN")
    }
    
    model_summary_tab <- data.frame(
        analysis_type = paste0("unified_", analysis_name),
        outcome = outcome_var,
        n_total = nrow(data),
        n_events = ifelse("coxph" %in% class(model_fit), 
                         sum(model_fit$y[, 2]), 
                         sum(as.numeric(model_fit$model[[1]]))),
        model_fitted = !is.null(model_fit),
        confounders_used = paste(confounders, collapse = ", "),
        notes = "Generated by unified table generation system",
        stringsAsFactors = FALSE
    )
    
    model_warnings <- c()
    if (!is.null(model_fit) && "glm" %in% class(model_fit)) {
        if (!model_fit$converged) {
            model_warnings <- c(model_warnings, "Model did not converge")
        }
    }
    if (!is.null(extreme_diagnostics) && length(extreme_diagnostics) > 0) {
        model_warnings <- c(model_warnings, "Extreme estimates detected")
    }
    if (!is.null(filtered_variables) && length(filtered_variables) > 0) {
        model_warnings <- c(model_warnings, "Variables were filtered due to extreme estimates")
    }
    model_warnings_text <- if (length(model_warnings) > 0) paste(model_warnings, collapse = "; ") else "None"
    
    model_diagnostics_tab <- data.frame(
        dataset_name = dataset_name,
        model_type = class(model_fit)[1],
        effect_measure = ifelse("coxph" %in% class(model_fit), "HR", "OR"),
        n_coefficients = length(coefs),
        model_converged = ifelse("glm" %in% class(model_fit), model_fit$converged, TRUE),
        log_likelihood = ifelse("glm" %in% class(model_fit), logLik(model_fit), NA),
        aic = AIC(model_fit),
        bic = BIC(model_fit),
        model_warnings = model_warnings_text,
        stringsAsFactors = FALSE
    )
    
    data_characteristics_tab <- data.frame(
        dataset_name = dataset_name,
        analysis_name = analysis_name,
        total_variables = length(c(predictor_vars, confounders)),
        predictor_variables = paste(predictor_vars, collapse = ", "),
        confounder_variables = paste(confounders, collapse = ", "),
        outcome_variable = outcome_var,
        sample_size = nrow(data),
        missing_data_pct = round(mean(is.na(data[c(predictor_vars, confounders, outcome_var)])) * 100, 1),
        stringsAsFactors = FALSE
    )
    
    other_level_details_tab <- data.frame(
        variable = character(),
        has_other_level = logical(),
        other_categories = character(),
        other_count = integer(),
        stringsAsFactors = FALSE
    )
    
    model_data <- model_fit$model
    for (var_name in names(model_data)) {
        if (var_name != "(weights)" && var_name != "(offset)") {
            var_data <- model_data[[var_name]]
            if (is.factor(var_data) || is.character(var_data)) {
                levels_data <- levels(var_data) %||% unique(var_data)
                if ("Other" %in% levels_data) {
                    other_count <- sum(var_data == "Other", na.rm = TRUE)
                    if (var_name %in% names(other_map) && length(other_map[[var_name]]) > 0) {
                        other_categories <- paste(other_map[[var_name]], collapse = ", ")
                    } else {
                        other_categories <- "Original categories not available in model data"
                    }
                    other_level_details_tab <- rbind(other_level_details_tab, data.frame(
                        variable = var_name,
                        has_other_level = TRUE,
                        other_categories = other_categories,
                        other_count = other_count,
                        stringsAsFactors = FALSE
                    ))
                }
            }
        }
    }
    
    excluded_rows_tab <- data.frame(
        term = character(),
        variable = character(),
        label = character(),
        estimate = numeric(),
        conf_low = numeric(),
        conf_high = numeric(),
        exclusion_reason = character(),
        stringsAsFactors = FALSE
    )
    
    factor_label_pvalues_tab <- data.frame(
        variable = character(),
        factor_label_pvalue = numeric(),
        test_type = character(),
        stringsAsFactors = FALSE
    )
    
    model_terms <- attr(terms(model_fit), "term.labels")
    variables_to_test <- unique(c(treatment_var, model_terms))
    
    for (var_name in variables_to_test) {
        var_confounders <- confounders[confounders != var_name]
        pval <- calculate_factor_label_pvalue(model_fit, var_name, data, outcome_var, var_confounders, treatment_var = treatment_var)
        factor_label_pvalues_tab <- rbind(factor_label_pvalues_tab, data.frame(
            variable = var_name,
            factor_label_pvalue = pval,
            test_type = "Likelihood Ratio Test",
            stringsAsFactors = FALSE
        ))
    }
    
    n_coefs <- length(coefs)
    n_conf_int <- nrow(conf_int)
    conf_int_padded <- matrix(NA, nrow = n_coefs, ncol = 2, 
                             dimnames = list(names(coefs), c("2.5 %", "97.5 %")))
    available_coefs <- intersect(names(coefs), rownames(conf_int))
    if (length(available_coefs) > 0) {
        conf_int_padded[available_coefs, ] <- conf_int[available_coefs, ]
    }
    if (length(available_coefs) < n_coefs) {
        missing_coefs <- setdiff(names(coefs), rownames(conf_int))
        log_enhanced(sprintf("Warning: Missing confidence intervals for coefficients: %s", 
                           paste(missing_coefs, collapse = ", ")), level = "WARN")
    }
    
    n_coefs <- length(coefs)
    p_values <- tryCatch({
        p_values_vector <- rep(NA, n_coefs)
        names(p_values_vector) <- names(coefs)
        available_coefs <- intersect(names(coefs), rownames(model_summary$coefficients))
        if (length(available_coefs) > 0) {
            col_names <- colnames(model_summary$coefficients)
            p_value_col <- which(col_names %in% c("Pr(>|z|)", "Pr(>|t|)", "Pr(>F)"))
            if (length(p_value_col) == 0) {
                p_value_col <- ncol(model_summary$coefficients)
                log_enhanced(sprintf("Warning: Could not find p-value column, using last column (%d)", p_value_col), level = "WARN")
            } else {
                p_value_col <- p_value_col[1]
            }
            p_values_vector[available_coefs] <- as.numeric(model_summary$coefficients[available_coefs, p_value_col])
        }
        p_values_vector
    }, error = function(e) {
        log_enhanced(sprintf("Error extracting p-values: %s", e$message), level = "WARN")
        rep(NA, n_coefs)
    })
    
    factor_label_pvalue_map <- setNames(
        factor_label_pvalues_tab$factor_label_pvalue,
        factor_label_pvalues_tab$variable
    )
    
    variable_names <- sapply(names(coefs), function(term) {
        if (grepl("^[a-zA-Z_]+[A-Z]", term)) {
            base_name <- sub("^([a-zA-Z_]+?)[A-Z].*", "\\1", term)
            if (base_name == term) {
                term
            } else {
                base_name
            }
        } else {
            term
        }
    })
    
    factor_label_pvalues_for_coefs <- sapply(variable_names, function(var_name) {
        if (var_name %in% names(factor_label_pvalue_map)) {
            factor_label_pvalue_map[[var_name]]
        } else {
            NA
        }
    })
    
    is_survival_model <- "coxph" %in% class(model_fit)
    effect_measure <- ifelse(is_survival_model, "HR", "OR")
    
    raw_model_output_tab <- data.frame(
        variable = names(coefs),
        variable_base = variable_names,
        log_coefficient = as.numeric(coefs),
        log_ci_lower = as.numeric(conf_int_padded[, 1]),
        log_ci_upper = as.numeric(conf_int_padded[, 2]),
        hazard_ratio = if(is_survival_model) exp(as.numeric(coefs)) else NA,
        hr_ci_lower = if(is_survival_model) exp(as.numeric(conf_int_padded[, 1])) else NA,
        hr_ci_upper = if(is_survival_model) exp(as.numeric(conf_int_padded[, 2])) else NA,
        odds_ratio = if(!is_survival_model) exp(as.numeric(coefs)) else NA,
        or_ci_lower = if(!is_survival_model) exp(as.numeric(conf_int_padded[, 1])) else NA,
        or_ci_upper = if(!is_survival_model) exp(as.numeric(conf_int_padded[, 2])) else NA,
        p_value = p_values,
        row_type = "Coefficient",
        inclusion_status = "Included",
        filtering_reason = "None",
        stringsAsFactors = FALSE
    )
    
    categorical_variables <- c()
    continuous_variables <- c()
    
    for (var_name in factor_label_pvalues_tab$variable) {
        if (var_name %in% names(data)) {
            if (is.factor(data[[var_name]]) || is.character(data[[var_name]])) {
                categorical_variables <- c(categorical_variables, var_name)
            } else if (is.numeric(data[[var_name]])) {
                continuous_variables <- c(continuous_variables, var_name)
            }
        } else {
            categorical_variables <- c(categorical_variables, var_name)
        }
    }
    
    factor_label_rows <- data.frame(
        variable = factor_label_pvalues_tab$variable[factor_label_pvalues_tab$variable %in% categorical_variables],
        variable_base = factor_label_pvalues_tab$variable[factor_label_pvalues_tab$variable %in% categorical_variables],
        log_coefficient = NA,
        log_ci_lower = NA,
        log_ci_upper = NA,
        hazard_ratio = NA,
        hr_ci_lower = NA,
        hr_ci_upper = NA,
        odds_ratio = NA,
        or_ci_lower = NA,
        or_ci_upper = NA,
        p_value = factor_label_pvalues_tab$factor_label_pvalue[factor_label_pvalues_tab$variable %in% categorical_variables],
        row_type = "Factor Label",
        inclusion_status = "Included",
        filtering_reason = "None",
        stringsAsFactors = FALSE
    )
    
    raw_model_output_tab <- rbind(factor_label_rows, raw_model_output_tab)
    
    sort_order <- mapply(custom_order, raw_model_output_tab$variable, raw_model_output_tab$row_type)
    raw_model_output_tab <- raw_model_output_tab[order(sort_order), ]
    
    excluded_variables <- c()
    if (nrow(excluded_rows_tab) > 0) {
        excluded_variables <- unique(excluded_rows_tab$variable[!is.na(excluded_rows_tab$variable)])
        log_enhanced(sprintf("Found %d variables in excluded rows: %s", 
                           length(excluded_variables), paste(excluded_variables, collapse = ", ")), 
                    level = "DEBUG")
        for (var_name in excluded_variables) {
            var_rows <- which(raw_model_output_tab$variable == var_name)
            if (length(var_rows) > 0) {
                raw_model_output_tab$inclusion_status[var_rows] <- "Filtered"
                raw_model_output_tab$filtering_reason[var_rows] <- "Extreme estimate or convergence issue"
                log_enhanced(sprintf("Marked variable %s as Filtered", var_name), level = "DEBUG")
            }
        }
    }
    
    log_enhanced("DEBUG: Starting diagnostic filtering logic using sophisticated detection", level = "DEBUG")
    
    coeff_rows <- raw_model_output_tab$row_type == "Coefficient"
    if (any(coeff_rows)) {
        if ("coxph" %in% class(model_fit)) {
            effect_measure <- "HR"
        } else if ("glm" %in% class(model_fit)) {
            effect_measure <- "OR"
        } else {
            effect_measure <- "MD"
        }
        
        diagnostic_extreme_result <- detect_extreme_regression_estimates(
            estimate = raw_model_output_tab$log_coefficient[coeff_rows],
            ci_lower = raw_model_output_tab$log_ci_lower[coeff_rows],
            ci_upper = raw_model_output_tab$log_ci_upper[coeff_rows],
            effect_measure = effect_measure,
            is_exponentiated = FALSE
        )
        
        if (length(diagnostic_extreme_result$extreme_indices) > 0) {
            coeff_indices <- which(coeff_rows)
            extreme_full_indices <- coeff_indices[diagnostic_extreme_result$extreme_indices]
            raw_model_output_tab$inclusion_status[extreme_full_indices] <- "Filtered"
            raw_model_output_tab$filtering_reason[extreme_full_indices] <- diagnostic_extreme_result$exclusion_reasons
            log_enhanced(sprintf("Marked %d variables as Filtered using sophisticated detection", 
                               length(extreme_full_indices)), level = "DEBUG")
            for (i in seq_along(extreme_full_indices)) {
                idx <- extreme_full_indices[i]
                log_enhanced(sprintf("DEBUG: Row %d (%s) filtered: %s", 
                                   idx, raw_model_output_tab$variable[idx], 
                                   diagnostic_extreme_result$exclusion_reasons[i]), level = "DEBUG")
            }
        }
    }
    
    infinite_ci_mask <- is.infinite(raw_model_output_tab$log_ci_upper) | is.infinite(raw_model_output_tab$log_ci_lower)
    raw_model_output_tab$inclusion_status[infinite_ci_mask] <- "Filtered"
    raw_model_output_tab$filtering_reason[infinite_ci_mask] <- "Infinite CI"
    
    na_estimate_mask <- is.na(raw_model_output_tab$log_coefficient) & raw_model_output_tab$row_type != "Factor Label"
    raw_model_output_tab$inclusion_status[na_estimate_mask] <- "Filtered"
    raw_model_output_tab$filtering_reason[na_estimate_mask] <- "NA estimate (convergence issue)"
    
    if (!is.null(filtered_variables) && length(filtered_variables) > 0) {
        log_enhanced(sprintf("DEBUG: Marking %d variables as filtered based on table output", length(filtered_variables)), level = "DEBUG")
        
        for (filtered_var in filtered_variables) {
            var_rows <- grep(paste0("^", filtered_var), raw_model_output_tab$variable)
            if (length(var_rows) > 0) {
                raw_model_output_tab$inclusion_status[var_rows] <- "Filtered"
                var_row_with_reason <- var_rows[raw_model_output_tab$filtering_reason[var_rows] != "None"][1]
                for (row_idx in var_rows) {
                    row_variable <- raw_model_output_tab$variable[row_idx]
                    row_reason <- "Filtered from table (specific reason not available)"
                    if (!is.na(raw_model_output_tab$filtering_reason[row_idx]) && 
                        raw_model_output_tab$filtering_reason[row_idx] != "None" &&
                        raw_model_output_tab$filtering_reason[row_idx] != "") {
                        next
                    } else {
                        if (!is.null(extreme_diagnostics) && !is.null(extreme_diagnostics$exclusion_reasons)) {
                            extreme_term_index <- which(extreme_diagnostics$extreme_terms == row_variable)
                            if (length(extreme_term_index) > 0) {
                                row_reason <- extreme_diagnostics$exclusion_reasons[extreme_term_index[1]]
                                log_enhanced(sprintf("DEBUG: Found table-level reason for %s: %s", row_variable, row_reason), level = "DEBUG")
                            } else {
                                if (grepl("^", filtered_var, row_variable)) {
                                    row_reason <- sprintf("Variable '%s' filtered due to extreme estimates or convergence issues", filtered_var)
                                } else {
                                    row_reason <- sprintf("Variable '%s' filtered - all coefficients had extreme estimates or convergence issues", filtered_var)
                                }
                                log_enhanced(sprintf("DEBUG: Generated specific reason for %s: %s", row_variable, row_reason), level = "DEBUG")
                            }
                        } else {
                            if (grepl("^", filtered_var, row_variable)) {
                                row_reason <- sprintf("Variable '%s' filtered due to extreme estimates or convergence issues", filtered_var)
                            } else {
                                row_reason <- sprintf("Variable '%s' filtered - all coefficients had extreme estimates or convergence issues", filtered_var)
                            }
                            log_enhanced(sprintf("DEBUG: Generated specific reason for %s: %s", row_variable, row_reason), level = "DEBUG")
                        }
                    }
                    raw_model_output_tab$filtering_reason[row_idx] <- row_reason
                }
                log_enhanced(sprintf("DEBUG: Marked variable %s as filtered with individual reasons for each term", filtered_var), level = "DEBUG")
            }
        }
    }
    
    excluded_mask <- raw_model_output_tab$inclusion_status == "Filtered"
    if (any(excluded_mask)) {
        excluded_rows_tab <- data.frame(
            variable = raw_model_output_tab$variable[excluded_mask],
            variable_base = raw_model_output_tab$variable_base[excluded_mask],
            log_coefficient = raw_model_output_tab$log_coefficient[excluded_mask],
            log_ci_lower = raw_model_output_tab$log_ci_lower[excluded_mask],
            log_ci_upper = raw_model_output_tab$log_ci_upper[excluded_mask],
            hazard_ratio = raw_model_output_tab$hazard_ratio[excluded_mask],
            hr_ci_lower = raw_model_output_tab$hr_ci_lower[excluded_mask],
            hr_ci_upper = raw_model_output_tab$hr_ci_upper[excluded_mask],
            odds_ratio = raw_model_output_tab$odds_ratio[excluded_mask],
            or_ci_lower = raw_model_output_tab$or_ci_lower[excluded_mask],
            or_ci_upper = raw_model_output_tab$or_ci_upper[excluded_mask],
            p_value = raw_model_output_tab$p_value[excluded_mask],
            row_type = raw_model_output_tab$row_type[excluded_mask],
            exclusion_reason = raw_model_output_tab$filtering_reason[excluded_mask],
            stringsAsFactors = FALSE
        )
    }
    
    filtered_count <- sum(raw_model_output_tab$inclusion_status == "Filtered", na.rm = TRUE)
    remaining_count <- sum(raw_model_output_tab$inclusion_status == "Included", na.rm = TRUE)
    excluded_count <- if (nrow(excluded_rows_tab) > 0) {
        length(unique(excluded_rows_tab$variable[!is.na(excluded_rows_tab$variable)]))
    } else {
        0
    }
    final_filtered_count <- max(filtered_count, excluded_count)
    
    main_predictor_filtered <- FALSE
    if (!is.null(predictor_vars) && length(predictor_vars) > 0) {
        for (pred_var in predictor_vars) {
            if (!(pred_var %in% raw_model_output_tab$variable)) {
                main_predictor_filtered <- TRUE
                break
            }
            var_rows <- grep(paste0("^", pred_var), raw_model_output_tab$variable)
            if (length(var_rows) > 0) {
                coeff_rows <- var_rows[raw_model_output_tab$row_type[var_rows] == "Coefficient"]
                if (length(coeff_rows) > 0) {
                    all_filtered <- all(raw_model_output_tab$inclusion_status[coeff_rows] == "Filtered")
                    if (all_filtered) {
                        main_predictor_filtered <- TRUE
                        break
                    }
                }
            }
        }
    }
    
    filtering_summary_tab <- data.frame(
        total_coefficients = nrow(raw_model_output_tab),
        extreme_estimates_removed = final_filtered_count,
        rows_removed = final_filtered_count,
        sparse_table_warning = FALSE,
        confint_error = all(is.na(conf_int)),
        remaining_coefficients = nrow(raw_model_output_tab) - final_filtered_count,
        table_has_meaningful_content = (nrow(raw_model_output_tab) - final_filtered_count) > 0,
        main_predictor_filtered = main_predictor_filtered
    )
    
    return(list(
        model_summary = model_summary_tab,
        model_diagnostics_tab = model_diagnostics_tab,
        data_characteristics = data_characteristics_tab,
        other_level_details = other_level_details_tab,
        excluded_rows = excluded_rows_tab,
        raw_model_output = raw_model_output_tab,
        filtering_summary = filtering_summary_tab
    ))
}

#' Get list of variables that were completely removed from the table
#'
#' @param table_result gtsummary table object
#' @param model_fit Fitted model object
#' @return Character vector of variable names that were completely removed
get_filtered_variables_from_table <- function(table_result, model_fit) {
    model_terms <- attr(terms(model_fit), "term.labels")
    model_var_names <- unique(c("treatment_group", model_terms))
    table_vars <- unique(table_result$table_body$variable)
    removed_vars <- setdiff(model_var_names, table_vars)
    return(removed_vars)
}

#' Remove variables that have only reference levels or extreme estimates (orphaned variables)
#'
#' @param table gtsummary table object
#' @param model_fit Fitted model object
#' @return Processed gtsummary table object
remove_orphaned_variables <- function(table, model_fit) {
    table_data <- table$table_body
    is_exponentiated <- any(grepl("OR|HR", table$table_body$coefficients_label, ignore.case = TRUE))
    valid_rows <- which(!is.na(suppressWarnings(as.numeric(table_data$estimate))))
    if (length(valid_rows) > 0) {
        extreme_result <- detect_extreme_regression_estimates(
            estimate = as.numeric(table_data$estimate[valid_rows]),
            ci_lower = as.numeric(table_data$conf.low[valid_rows]),
            ci_upper = as.numeric(table_data$conf.high[valid_rows]),
            effect_measure = ifelse(is_exponentiated, "OR", "estimate"),
            is_exponentiated = is_exponentiated
        )
        if (length(extreme_result$extreme_indices) > 0) {
            extreme_original_indices <- valid_rows[extreme_result$extreme_indices]
            orphaned_vars <- unique(table_data$variable[extreme_original_indices])
            if (length(orphaned_vars) > 0) {
                log_enhanced(sprintf("Removing variables with extreme estimates detected by centralized function: %s", 
                                   paste(orphaned_vars, collapse = ", ")), level = "INFO")
                table$table_body <- table_data[!table_data$variable %in% orphaned_vars, ]
            }
        } else {
            log_enhanced("No variables with extreme estimates found by centralized function.", level = "INFO")
        }
    } else {
        log_enhanced("No valid numeric estimates to check for extreme values.", level = "INFO")
    }
    return(table)
}

#' Calculate F-test p-value for linear regression models
#'
#' @param model_fit Fitted linear model object
#' @param variable_name Name of the variable to test
#' @param data Data frame used for the model
#' @param outcome_var Name of the outcome variable
#' @param confounders Character vector of confounders
#' @return Numeric p-value (or NA on failure)
calculate_ftest_pvalue <- function(model_fit, variable_name, data, outcome_var, confounders) {
    tryCatch({
        if (require(car, quietly = TRUE)) {
            anova_result <- car::Anova(model_fit, type = 3)
            if (variable_name %in% rownames(anova_result)) {
                return(anova_result[variable_name, "Pr(>F)"])
            } else {
                warning(sprintf("Variable '%s' not found in Anova result", variable_name))
                return(NA)
            }
        } else {
            warning("car package not available for F-test")
            return(NA)
        }
    }, error = function(e) {
        warning(sprintf("F-test failed for variable '%s': %s", variable_name, e$message))
        return(NA)
    })
}

#' Calculate Wald test p-value as fallback
#'
#' @param model_fit Fitted model object
#' @param variable_name Name of the variable to test
#' @return Numeric p-value (or NA on failure)
calculate_wald_pvalue <- function(model_fit, variable_name) {
    tryCatch({
        summary_result <- summary(model_fit)
        if ("coefficients" %in% names(summary_result)) {
            var_coefs <- grep(paste0("^", variable_name), rownames(summary_result$coefficients), value = TRUE)
            if (length(var_coefs) > 0) {
                var_pvals <- summary_result$coefficients[var_coefs, 4]
                min_pval <- suppressWarnings(min(var_pvals, na.rm = TRUE))
                if (is.finite(min_pval)) {
                    warning(sprintf("Using minimum Wald p-value for variable '%s': %f", variable_name, min_pval))
                    return(min_pval)
                }
            }
        }
        warning(sprintf("Wald test failed for variable '%s'", variable_name))
        return(NA)
    }, error = function(e) {
        warning(sprintf("Wald test failed for variable '%s': %s", variable_name, e$message))
        return(NA)
    })
}

#' Calculate factor label p-value using appropriate test for model type
#'
#' @param model_fit Fitted model object
#' @param variable_name Variable to test
#' @param data Data frame
#' @param outcome_var Outcome variable name
#' @param confounders Character vector of confounders
#' @param treatment_var Treatment variable name (default: "treatment_group")
#' @return Numeric p-value (or NA on failure)
calculate_factor_label_pvalue <- function(model_fit, variable_name, data, outcome_var, confounders, treatment_var = "treatment_group") {
    model_type <- detect_model_type(model_fit)
    var_confounders <- confounders[confounders != variable_name]
    switch(model_type,
        "linear" = {
            calculate_ftest_pvalue(model_fit, variable_name, data, outcome_var, var_confounders)
        },
        "logistic" = {
            calculate_variable_overall_significance(
                data, variable_name, outcome_var,
                treatment_var = treatment_var,
                confounders = var_confounders,
                outcome_type = model_type_to_outcome_type(model_type)
            )
        },
        "cox" = {
            base <- gsub("_event$", "", outcome_var)
            time_months <- paste0("tt_", base, "_months")
            time_years <- paste0("tt_", base, "_years")
            if (time_months %in% names(data)) {
                time_var <- time_months
            } else if (time_years %in% names(data)) {
                time_var <- time_years
            } else {
                warning(sprintf("No time variable found for outcome '%s'", outcome_var))
                return(NA)
            }
            tryCatch({
                calculate_variable_overall_significance(
                    data, variable_name, outcome_var,
                    treatment_var = treatment_var,
                    confounders = var_confounders,
                    outcome_type = model_type_to_outcome_type(model_type),
                    time_var = time_var,
                    event_var = outcome_var
                )
            }, error = function(e) {
                warning(sprintf("Cox p-value calculation failed: %s", e$message))
                NA
            })
        },
        "other_glm" = {
            calculate_wald_pvalue(model_fit, variable_name)
        },
        {
            warning(sprintf("Unsupported model type '%s' for variable '%s'", model_type, variable_name))
            NA
        }
    )
}
